OpenSourcePolitics/decidim

decidim-core/app/commands/decidim/create_registration.rb, decidim-core/app/commands/decidim/invite_user.rb, decidim-core/app/forms/decidim/registration_form.rb
https://github.com/OpenSourcePolitics/decidim-osp/issues/4
=> Make newsletter and email notfications default to true

decidim-proposals/config/locales/fr.yml
=> edit translations

decidim-accountability/config/locales/fr.yml, decidim-admin/config/locales/fr.yml, decidim-assemblies/config/locales/fr.yml, decidim-budgets/config/locales/fr.yml, decidim-core/config/locales/en.yml, decidim-core/config/locales/fr.yml, decidim-debates/config/locales/fr.yml, decidim-meetings/config/locales/fr.yml, decidim-participatory_processes/config/locales/fr.yml, decidim-proposals/config/locales/fr.yml, decidim-verifications/app/services/decidim/dummy_authorization_handler.rb, decidim-verifications/config/locales/fr.yml
- Remove the ending-with-an-X validation for the document number that the user/admin enters through the dummy authorization handler
- Fix trad in french for the text fields
- Fix the trads with what has been updated on Crowdin
- Fixes #66
=> Update dummy authorization handler

decidim-accountability/config/locales/fr.yml, decidim-admin/config/locales/fr.yml, decidim-assemblies/config/locales/fr.yml, decidim-budgets/config/locales/fr.yml, decidim-core/config/locales/en.yml, decidim-core/config/locales/fr.yml, decidim-debates/config/locales/fr.yml, decidim-meetings/config/locales/fr.yml, decidim-participatory_processes/config/locales/fr.yml, decidim-proposals/config/locales/fr.yml, decidim-verifications/app/services/decidim/dummy_authorization_handler.rb, decidim-verifications/config/locales/fr.yml
- Remove the ending-with-an-X validation for the document number that the user/admin enters through the dummy authorization handler
- Fix trad in french for the text fields
- Fix the trads with what has been updated on Crowdin
- Fixes #66
=> Update dummy authorization handler for Angers

decidim-admin/config/locales/fr.yml, decidim-assemblies/config/locales/fr.yml, decidim-core/config/locales/fr.yml, decidim-meetings/config/locales/fr.yml, decidim-participatory_processes/config/locales/fr.yml, decidim-proposals/config/locales/fr.yml, decidim-system/config/locales/fr.yml, decidim-verifications/config/locales/fr.yml
Add customized french translation of OSP to 0.10-stable
=> 0.10/fix trad

decidim-admin/app/controllers/decidim/admin/moderations_controller.rb
Now as an admin I can hide content that has been reported
- Fixes #78
=> fix reporting of content

decidim-debates/lib/decidim/debates/feature.rb
Now as a user I can comment in debates
=> 0.9 stable fix debates

decidim-core/app/validators/etiquette_validator.rb, decidim-proposals/app/views/decidim/proposals/proposals/_count.html.erb, decidim-proposals/config/locales/en.yml, decidim-proposals/config/locales/fr.yml
=> Counter error

decidim-core/app/assets/stylesheets/decidim/extras/_register_form.scss, decidim-core/app/assets/stylesheets/decidim/modules/_signup.scss, decidim-core/app/views/decidim/devise/registrations/new.html.erb, decidim-core/config/locales/en.yml, decidim-core/config/locales/fr.yml, decidim-core/config/locales/nl.yml, decidim-core/spec/system/registration_unbundled_consent_spec.rb
From CodiTramuntana
On the user registration page, separate better what belongs to the TOS (Terms Of Service) and what belongs to the newsletter.
=> Unbundled consent on user registration

.circleci/config.yml
Update of CircleCi build architecture
=> :green_heart: Add new ci build architecture

decidim-meetings/config/locales/fr.yml
=> Add missing translation

.circleci/config.yml
Add codeclimate key in order to know the code diff coverazge and improve our work.
=> Add OSP code coverage reporter

.circleci/config.yml
Use circle-ci to notify our rocket chat
=> Use circle-ci to notify our rocket chat

Gemfile.lock, decidim-admin/config/locales/fr.yml, decidim-generators/Gemfile.lock, decidim-meetings/config/locales/fr.yml
Fix translations
- Fixes #238
- Fixes #237 
- Fixes #235
=> 0.12 stable fix translations

decidim-budgets/config/locales/fr.yml
=> Fix translation on budget project

decidim-budgets/config/locales/fr.yml
=> Fix translation

Gemfile.lock, decidim-generators/Gemfile.lock, decidim-surveys/config/locales/fr.yml
Fix translations on Survey component
- Fixes #239
=> Fix translations on Survey component

decidim-core/app/forms/decidim/attachment_form.rb, decidim-core/config/locales/fr.yml
Following Nancy's request, we update translations in the invitation email that were a bit weird.
=> Update decidim-core translations

decidim-budgets/config/locales/fr.yml
Fix translation missing/wrong on Angers new budget
- Fixes #272
=> Add new translations

CHANGELOG.md
=> :bug: typo merge

CHANGELOG.md, decidim-participatory_processes/app/views/decidim/participatory_processes/admin/participatory_processes/index.html.erb, decidim-participatory_processes/spec/system/admin/participatory_process_admin_manages_participatory_processes_spec.rb
Fix participatory processes pagination
=> Fix participatory processes pagination

CHANGELOG.md, decidim-proposals/lib/decidim/proposals/proposal_serializer.rb, decidim-proposals/spec/services/decidim/proposals/proposal_serializer_spec.rb
Exporting proposals address, latitude, longitude.
- Related to #506
- Fixes #564
=> Add geolocation to export

decidim-budgets/spec/shared/orders_examples.rb
=> Fix flaky test

CHANGELOG.md, decidim-comments/app/models/decidim/comments/comment.rb, decidim-comments/lib/decidim/comments/api/comment_type.rb, decidim-comments/spec/models/comment_spec.rb, decidim-comments/spec/types/comment_type_spec.rb
Backport Fix comment reply #4938
- Fixes #553
=> Backport Fix comment reply #4938

CHANGELOG.md, decidim-proposals/app/helpers/decidim/proposals/proposal_wizard_helper.rb, decidim-proposals/app/views/decidim/proposals/collaborative_drafts/_wizard_aside.html.erb, decidim-proposals/app/views/decidim/proposals/collaborative_drafts/compare.html.erb, decidim-proposals/app/views/decidim/proposals/collaborative_drafts/complete.html.erb, decidim-proposals/app/views/decidim/proposals/collaborative_drafts/new.html.erb, decidim-proposals/app/views/decidim/proposals/proposals/_proposal_preview.html.erb, decidim-proposals/app/views/decidim/proposals/proposals/compare.html.erb, decidim-proposals/config/locales/en.yml, decidim-proposals/spec/system/proposal_wizard_spec.rb
Backport: https://github.com/decidim/decidim/pull/4976/
=> Fix proposal wizard back button

CHANGELOG.md, decidim-proposals/app/permissions/decidim/proposals/permissions.rb, decidim-proposals/app/views/decidim/proposals/collaborative_drafts/_accept_request_access_form.html.erb, decidim-proposals/app/views/decidim/proposals/collaborative_drafts/_collaborator_requests.html.erb, decidim-proposals/app/views/decidim/proposals/collaborative_drafts/_reject_request_access_form.html.erb, decidim-proposals/spec/system/collaborative_drafts_spec.rb
Backport: https://github.com/decidim/decidim/pull/4712
=> Change collaborative draft contributors permissions

CHANGELOG.md, decidim-core/app/controllers/decidim/static_map_controller.rb, decidim-core/spec/controllers/static_map_controller_spec.rb
Backport: https://github.com/decidim/decidim/pull/4830
=> Fix redirect to static map view after login

CHANGELOG.md, decidim-core/app/assets/javascripts/decidim/input_hashtags.js.es6, decidim-core/vendor/assets/javascripts/tribute.js, decidim-meetings/app/views/decidim/meetings/admin/meetings/_form.html.erb, decidim-proposals/lib/decidim/content_parsers/proposal_parser.rb, decidim-proposals/spec/lib/decidim/content_parsers/proposal_parser_spec.rb
Backport: https://github.com/decidim/decidim/pull/4984/
=> Bring #4980 and #4978 to 0.16

CHANGELOG.md, decidim-proposals/app/controllers/decidim/proposals/collaborative_drafts_controller.rb, decidim-proposals/app/controllers/decidim/proposals/proposals_controller.rb, decidim-proposals/app/models/decidim/proposals/collaborative_draft.rb
Backport: https://github.com/decidim/decidim/pull/4706/files
=> Fix unhideable reported collaborative drafts and mail jobs

decidim-admin/config/locales/fr.yml
Add translations for organization
- Fixes #549
=> Add translations for organization

CHANGELOG.md, decidim-core/spec/models/decidim/attachment_spec.rb, decidim-proposals/app/commands/decidim/proposals/publish_collaborative_draft.rb, decidim-proposals/db/migrate/20190416112905_add_collaborative_draft_origin_to_proposal.rb, decidim-proposals/lib/decidim/proposals/proposal_serializer.rb, decidim-proposals/spec/commands/decidim/proposals/create_proposal_spec.rb, decidim-proposals/spec/commands/decidim/proposals/publish_collaborative_draft_spec.rb, decidim-proposals/spec/commands/decidim/proposals/publish_proposal_spec.rb, decidim-proposals/spec/services/decidim/proposals/proposal_serializer_spec.rb
Proposals export enhancements.
=> Proposals export enhancements.

decidim-budgets/spec/shared/orders_examples.rb
Fix flaky budget test
- Fixes #?
=> Fix budget test

decidim-core/app/assets/stylesheets/decidim/modules/_buttons.scss
=> Fix hollow text color

decidim-assemblies/config/locales/fr.yml
=> Add new traduction for assemblies help filter

decidim-core/app/assets/stylesheets/decidim/modules/_buttons.scss
Fix/newsletter pop up
- Fixes #644
Codegram's staging: 
Our version :
=> Fix Secondary color

decidim-admin/app/views/decidim/admin/organization_appearance/_form.html.erb
=> Fix double snippet

decidim-core/config/locales/en.yml, decidim-system/app/assets/stylesheets/decidim/system/_logs.scss, decidim-system/app/assets/stylesheets/decidim/system/application.scss, decidim-system/app/controllers/decidim/system/logs_controller.rb, decidim-system/app/views/decidim/system/logs/index.html.erb, decidim-system/config/locales/en.yml, decidim-system/config/routes.rb, decidim-system/lib/decidim/system/engine.rb, decidim-system/spec/helpers/menu_helper_spec.rb, decidim-system/spec/system/logs_spec.rb
=> Add logs view for system

decidim-admin/app/controllers/decidim/admin/moderations_controller.rb, decidim-admin/app/controllers/decidim/admin/upstream_moderations_controller.rb, decidim-admin/app/views/decidim/admin/moderations/index.html.erb, decidim-admin/app/views/decidim/admin/upstream_moderations/index.html.erb, decidim-admin/config/locales/en.yml, decidim-admin/config/locales/fr.yml, decidim-core/app/models/decidim/moderation.rb, decidim-core/app/models/decidim/upstream_moderation.rb
Fix/upstream moderation + moderation order
- Fixes #721
=> Fix/upstream moderation + moderation order

decidim-proposals/app/models/decidim/proposals/proposal.rb, decidim-sortitions/app/queries/decidim/sortitions/admin/participatory_space_proposals.rb, decidim-sortitions/spec/queries/decidim/sortitions/admin/participatory_space_proposals_spec.rb
=> Don't include drafts in sortitions

decidim-participatory_processes/app/permissions/decidim/participatory_processes/permissions.rb, decidim-participatory_processes/spec/permissions/decidim/participatory_processes/permissions_spec.rb, decidim-participatory_processes/spec/system/admin/invite_process_admin_spec.rb, decidim-participatory_processes/spec/system/admin/participatory_process_admin_manages_participatory_process_private_users_spec.rb
=> Fix permissions for participatory process admin

decidim-core/app/assets/stylesheets/decidim/modules/_buttons.scss
Fix/newsletter secondary button color
=> Fix newsletter secondary button color

config/i18n-tasks.yml, decidim-core/app/assets/javascripts/decidim/user_registrations.js.es6, decidim-core/app/assets/stylesheets/decidim/modules/_modules.scss, decidim-core/app/assets/stylesheets/decidim/modules/_shared.scss, decidim-core/app/assets/stylesheets/decidim/modules/_signup.scss, decidim-core/app/commands/decidim/create_registration.rb, decidim-core/app/forms/decidim/registration_form.rb, decidim-core/app/views/decidim/devise/registrations/new.html.erb, decidim-core/app/views/decidim/devise/shared/_links.html.erb, decidim-core/app/views/decidim/devise/shared/_omniauth_buttons.html.erb, decidim-core/config/locales/en.yml, decidim-core/config/locales/fr.yml, decidim-core/db/migrate/20191211133811_add_registration_metadata_to_decidim_users.rb, decidim-core/lib/decidim/core/test/factories.rb, decidim-core/spec/commands/decidim/create_registration_spec.rb, decidim-core/spec/controllers/registrations_controller_spec.rb, decidim-core/spec/forms/registration_form_spec.rb, decidim-core/spec/system/authentication_spec.rb, decidim-core/spec/system/registration_spec.rb, decidim-core/spec/system/registration_unbundled_consent_spec.rb
Add custom fields on registration
=> Add custom fields on registration

decidim-comments/lib/decidim/comments/comment_serializer.rb, decidim-comments/spec/lib/decidim/comments/comment_serializer_spec.rb, decidim-forms/config/locales/en.yml, decidim-forms/config/locales/fr.yml, decidim-forms/lib/decidim/forms/user_answers_serializer.rb, decidim-forms/spec/serializers/decidim/forms/user_answer_serializer_spec.rb, decidim-proposals/lib/decidim/proposals/proposal_serializer.rb, decidim-proposals/spec/services/decidim/proposals/proposal_serializer_spec.rb
Add authors_registration_metadata to exports
=> Add authors_registration_metadata to exports

decidim-core/app/controllers/decidim/application_controller.rb, decidim-core/app/controllers/decidim/components/base_controller.rb, decidim-initiatives/app/cells/decidim/initiatives/initiative_m_cell.rb, decidim-initiatives/app/views/decidim/initiatives/initiatives/show.html.erb
=> add deepl translation to initiatives

decidim-proposals/app/helpers/decidim/proposals/application_helper.rb, decidim-proposals/app/services/decidim/proposals/proposal_search.rb, decidim-proposals/spec/services/decidim/proposals/proposal_search_spec.rb, decidim-proposals/spec/system/filter_proposals_spec.rb
=> Fix proposal search

decidim-core/app/assets/javascripts/decidim/user_registrations.js.es6, decidim-core/spec/system/registration_spec.rb
=> Backport populate improvement

decidim-comments/app/models/decidim/comments/comment.rb, decidim-core/app/cells/decidim/activities_cell.rb, decidim-core/app/cells/decidim/content_blocks/last_activity_cell.rb, decidim-core/app/models/decidim/action_log.rb, decidim-core/app/models/decidim/component.rb, decidim-core/lib/decidim/has_component.rb, decidim-core/lib/decidim/has_private_users.rb, decidim-core/lib/decidim/view_model.rb, decidim-core/spec/cells/decidim/content_blocks/last_activity_cell_spec.rb, decidim-core/spec/models/decidim/action_log_spec.rb, decidim-core/spec/system/last_activity_spec.rb, decidim-dev/lib/decidim/dev/test/rspec_support/warden.rb
🎩 What? Why?
In the list of Last Activity, the comments that have been moderated appear.
📌 Related Issues
Related to https://meta.decidim.org/processes/bug-report/f/210/proposals/14857
📋 Subtasks
=> Backport hide reported content 

decidim-core/app/serializers/decidim/exporters/participatory_space_components_serializer.rb, decidim-core/app/serializers/decidim/importers/participatory_space_components_importer.rb, decidim-core/lib/decidim/core/test/factories.rb, decidim-core/spec/serializers/decidim/exporters/participatory_space_components_serializer_spec.rb, decidim-core/spec/serializers/decidim/importers/participatory_space_components_importer_spec.rb, decidim-participatory_processes/app/serializers/decidim/participatory_processes/participatory_process_importer.rb
Backport export_participatory_process_fix
=> Backport export_participatory_process_fix

CHANGELOG.md, decidim-core/app/uploaders/decidim/banner_image_uploader.rb
Backport banner image uploader keeping the banner image versionning ( md, xs ).
=> Backport banner image uploader

decidim-initiatives/app/cells/decidim/initiatives_votes/vote/show.erb, decidim-initiatives/app/cells/decidim/initiatives_votes/vote_cell.rb, decidim-initiatives/app/controllers/decidim/initiatives/initiative_signatures_controller.rb, decidim-initiatives/app/forms/decidim/initiatives/vote_form.rb, decidim-initiatives/app/views/decidim/initiatives/initiative_signatures/fill_personal_data.html.erb, decidim-initiatives/config/locales/en.yml, decidim-initiatives/config/locales/fr.yml, decidim-initiatives/spec/forms/vote_form_spec.rb, decidim-initiatives/spec/system/initiative_signing_spec.rb
Remove personal data fields in initiative vote form
- Related to https://github.com/OpenSourcePolitics/decidim/pull/928#issuecomment-621730172
=> Remove personal data fields in vote form

.github/labeler.yml, .github/workflows/label.yml, decidim-accountability/config/locales/nl.yml, decidim-admin/config/locales/nl.yml, decidim-assemblies/config/locales/nl.yml, decidim-blogs/config/locales/nl.yml, decidim-budgets/config/locales/nl.yml, decidim-comments/config/locales/nl.yml, decidim-conferences/config/locales/nl.yml, decidim-consultations/config/locales/nl.yml, decidim-core/config/locales/nl.yml, decidim-debates/config/locales/nl.yml, decidim-dev/config/locales/nl.yml, decidim-forms/config/locales/nl.yml, decidim-initiatives/config/locales/nl.yml, decidim-meetings/config/locales/nl.yml, decidim-pages/config/locales/nl.yml, decidim-participatory_processes/config/locales/nl.yml, decidim-proposals/config/locales/nl.yml, decidim-sortitions/config/locales/nl.yml, decidim-surveys/config/locales/nl.yml, decidim-system/config/locales/nl.yml, decidim-verifications/config/locales/nl.yml
Add missing translations for CultuurConnect
=> Add translations nl

CHANGELOG.md, decidim-core/lib/decidim/core/engine.rb, decidim-initiatives/app/controllers/decidim/initiatives/admin/initiatives_controller.rb, decidim-initiatives/app/jobs/decidim/initiatives/export_initiatives_job.rb, decidim-initiatives/app/models/decidim/initiative.rb, decidim-initiatives/app/permissions/decidim/initiatives/admin/permissions.rb, decidim-initiatives/app/serializers/decidim/initiatives/initiative_serializer.rb, decidim-initiatives/app/views/decidim/initiatives/admin/exports/_dropdown.html.erb, decidim-initiatives/app/views/decidim/initiatives/admin/initiatives/index.html.erb, decidim-initiatives/config/locales/en.yml, decidim-initiatives/lib/decidim/initiatives/admin_engine.rb, decidim-initiatives/lib/decidim/initiatives/participatory_space.rb, decidim-initiatives/spec/controllers/decidim/initiatives/admin/initiatives_controller_spec.rb, decidim-initiatives/spec/jobs/decidim/initiatives/export_initiatives_job_spec.rb, decidim-initiatives/spec/system/admin/export_spec.rb, decidim-initiatives/spec/system/initiatives_spec.rb
Allow admins to export initiatives.
https://meta.decidim.org/processes/roadmap/f/122/proposals/15123
=> Backport initiatives export

CHANGELOG.md, decidim-core/lib/decidim/core/engine.rb, decidim-initiatives/app/cells/decidim/initiatives/initiative_m_cell.rb, decidim-initiatives/app/controllers/decidim/initiatives/initiatives_controller.rb, decidim-initiatives/app/helpers/decidim/initiatives/application_helper.rb, decidim-initiatives/app/models/decidim/initiative.rb, decidim-initiatives/app/services/decidim/initiatives/initiative_search.rb, decidim-initiatives/app/views/decidim/initiatives/initiatives/_filters.html.erb, decidim-initiatives/config/locales/en.yml, decidim-initiatives/spec/services/decidim/initiatives/initiative_search_spec.rb, decidim-initiatives/spec/system/filter_initiatives_spec.rb, decidim-initiatives/spec/system/initiatives_spec.rb
Adapt initiatives search filters to the recent design used in proposals.
Metadecidim proposal: https://meta.decidim.org/processes/roadmap/f/122/proposals/15234
=> Backport initiatives search fo new design

config/i18n-tasks.yml, decidim-initiatives/app/commands/decidim/initiatives/vote_initiative.rb, decidim-initiatives/app/models/decidim/initiative.rb, decidim-initiatives/app/services/decidim/initiatives/diff_renderer.rb, decidim-initiatives/config/locales/en.yml, decidim-initiatives/spec/commands/decidim/initiatives/create_initiative_spec.rb, decidim-initiatives/spec/events/decidim/initiatives/admin/support_threshold_reached_event_spec.rb, decidim-initiatives/spec/shared/create_initiative_example.rb, decidim-initiatives/spec/system/initiatives_versions_spec.rb
Add missing translations
-  `fr.decidim.initiatives.show.badge_name.examinated`
-  `fr.decidim.initiatives.show.badge_name.debatted`
-  `fr.decidim.initiatives.show.badge_name.classified`
=> Add missing translations

decidim-initiatives/app/commands/decidim/initiatives/create_initiative.rb, decidim-initiatives/app/controllers/decidim/initiatives/create_initiative_controller.rb, decidim-initiatives/app/forms/decidim/initiatives/admin/initiative_form.rb, decidim-initiatives/app/forms/decidim/initiatives/initiative_form.rb, decidim-initiatives/app/views/decidim/initiatives/admin/initiatives/_form.html.erb, decidim-initiatives/app/views/decidim/initiatives/create_initiative/fill_data.html.erb, decidim-initiatives/spec/forms/initiative_form_spec.rb, decidim-initiatives/spec/shared/create_initiative_example.rb
Only admin can select an area to an initiative
=> Backport Only admin can select an area to an initiative

decidim-core/app/forms/decidim/account_form.rb, decidim-core/spec/forms/account_form_spec.rb
=> Forbid long name

decidim-initiatives/app/controllers/decidim/initiatives/initiatives_controller.rb, decidim-initiatives/app/forms/decidim/initiatives/admin/initiative_form.rb, decidim-initiatives/app/helpers/decidim/initiatives/application_helper.rb, decidim-initiatives/app/helpers/decidim/initiatives/initiative_helper.rb, decidim-initiatives/app/models/decidim/initiative.rb, decidim-initiatives/app/services/decidim/initiatives/initiative_search.rb, decidim-initiatives/app/views/decidim/initiatives/initiatives/_filters.html.erb, decidim-initiatives/config/locales/en.yml, decidim-initiatives/spec/system/filter_initiatives_spec.rb
Add new filter for custom states (Published, classified, examinated, debatted)
=> Fix custom state filter

decidim-initiatives/app/views/layouts/decidim/_initiative_header_steps.html.erb, decidim-initiatives/spec/system/initiative_spec.rb
Change the date in initiative banner
=> Remove start signature date

decidim-initiatives/app/views/decidim/initiatives/admin/initiatives/index.html.erb
Reintroduce commented signature count
- Related to https://github.com/OpenSourcePolitics/decidim/pull/987
=> Fix signature count

decidim-core/lib/decidim/exporters/csv.rb, decidim-core/lib/decidim/exporters/excel.rb, decidim-core/spec/lib/exporters/csv_spec.rb, decidim-core/spec/lib/exporters/excel_spec.rb
=> backport Add CSV Excel exporter sanitizer

decidim-core/lib/tasks/decidim_user_tasks.rake, decidim-core/spec/tasks/decidim_tasks_user_destroy_spec.rb
Allows to destroy multiple user accounts 
- Fixes #?
=> Feature rake destroy accounts

decidim-core/lib/tasks/decidim_user_tasks.rake, decidim-core/spec/tasks/decidim_tasks_user_destroy_spec.rb
Rake command that allows to destroy user accounts that match specified conditions
=> Backport destroy account command

decidim-core/app/views/layouts/decidim/_mailer_logo.html.erb, decidim-core/app/views/layouts/decidim/mailer.html.erb, decidim-initiatives/spec/mailers/decidim/initiatives/initiatives_mailer_spec.rb
add `rel="notrack"` on mail links
=> Add rel notrack attribute on mail links

decidim-core/app/views/decidim/export_mailer/data_portability_export.html.erb, decidim-core/app/views/decidim/notification_mailer/event_received.html.erb, decidim-core/app/views/devise/mailer/confirmation_instructions.html.erb, decidim-core/app/views/devise/mailer/invitation_instructions.html.erb, decidim-core/app/views/devise/mailer/invite_admin.html.erb, decidim-core/app/views/devise/mailer/invite_collaborator.html.erb, decidim-core/app/views/devise/mailer/invite_private_user.html.erb, decidim-core/app/views/devise/mailer/organization_admin_invitation_instructions.html.erb, decidim-core/app/views/devise/mailer/reset_password_instructions.html.erb, decidim-core/app/views/devise/mailer/unlock_instructions.html.erb
Add notrack attribute on devise mail links
=> add notrack mail links

decidim-admin/config/locales/en.yml, decidim-core/app/mailers/decidim/application_mailer.rb, decidim-system/app/forms/decidim/system/update_organization_form.rb, decidim-system/app/views/decidim/system/organizations/_smtp_settings.html.erb, decidim-system/config/locales/en.yml, decidim-system/db/migrate/20201012153759_update_smtp_from_label.rb, decidim-system/spec/commands/decidim/system/register_organization_spec.rb, decidim-system/spec/commands/decidim/system/update_organization_spec.rb
Backport corrections of `smtp_settings` done here https://github.com/OpenSourcePolitics/decidim/commit/e7b3852b74242d76590864e2c49554dee40f7d7c#diff-c3de2a5e220c73264b64ce55dcc85a4a
and here
https://github.com/OpenSourcePolitics/decidim/commit/81de8165a4cd0ba8f75f21b76186693d318e72be
- Fixes #?
=> Backport : `smtp_settings` correction

decidim-api/config/routes.rb
=> Opening commit :construction:

decidim-assemblies/spec/models/decidim/assembly_spec.rb
=> Fix assemblies ci

decidim-conferences/spec/models/decidim/conference_spec.rb
=> Fix conferences ci

decidim-forms/app/controllers/decidim/forms/concerns/has_questionnaire.rb, decidim-surveys/spec/system/unregistered_user_survey_spec.rb
=> Fix surveys ci

decidim-core/app/cells/decidim/card_m/header.erb, decidim-proposals/spec/system/proposals_spec.rb
=> Fix proposals ci

decidim-core/app/commands/decidim/destroy_account.rb, decidim-core/app/mailers/decidim/destroy_account_mailer.rb, decidim-core/app/views/decidim/destroy_account_mailer/notify.html.erb, decidim-core/config/locales/ca.yml, decidim-core/config/locales/en.yml, decidim-core/config/locales/es.yml, decidim-core/spec/commands/decidim/destroy_account_spec.rb, decidim-core/spec/mailers/destroy_account_mailer_spec.rb
=> Add notification for admins
