- decidim-core/vendor/assets/javascripts/datepicker-locales/foundation-datepicker.fr.js
French date format in datepicker in admin dashboard wasn't right. Now the format is set to dd/mm/yyyy
- Fixes #34
> Add format in french datepicker locale

- CHANGELOG.md
In order to keep a trace of our customization on Decidim i suggest that we had our dev on decidim changelog
> Add OSP changes in CHANGELOG

- decidim-core/app/controllers/decidim/devise/sessions_controller.rb
- decidim-core/lib/decidim/core.rb
- decidim-core/spec/controllers/sessions_controller_spec.rb
Because choice is important! Add an initialization variable that allows to skip first login_authorization
In your `config/initializers/decidim.rb` add the following line : 
```
config.skip_first_login_authorization = true
```
Default value is set to *false*
- Fixes #172
> 0.12 stable skip first login authorization

- CHANGELOG.md
- decidim-participatory_processes/app/cells/decidim/participatory_processes/process_m/tags.erb
- decidim-participatory_processes/spec/system/participatory_processes_spec.rb
Hashtags on Participatory Processes should only appear when the field is filled by the admin.
- Fixes #193
> Don't display '#' if there is no hashtag

- CHANGELOG.md
- decidim-core/spec/controllers/sessions_controller_spec.rb
The skip first login authorization option test was messing around and causing some inconsistency, this quick-fix stop this problem.
- Related to #221
> Fix unwanted mandatory tests execution

- decidim-admin/spec/system/admin_manages_navbar_links_spec.rb
The navbar links tests were inconsistent, this was due to a badly written test.
> Delete incorrect test

- CHANGELOG.md
- decidim-admin/app/controllers/decidim/admin/officializations_controller.rb
- decidim-admin/app/views/decidim/admin/officializations/index.html.erb
- decidim-admin/spec/system/admin_manages_officializations_spec.rb
The administrator can start a conversation directly from the back office with a user.
The administrator can also directly visit the user profile.
- #138
> [Backport] Add link to user profile and link to conversation from admin space.

- decidim-core/app/validators/etiquette_validator.rb
- decidim-core/spec/validators/etiquette_validator_spec.rb
- decidim-proposals/app/commands/decidim/proposals/admin/create_proposal.rb
- decidim-proposals/app/commands/decidim/proposals/create_proposal.rb
- decidim-proposals/app/commands/decidim/proposals/update_proposal.rb
- decidim-proposals/app/forms/decidim/proposals/admin/proposal_form.rb
- decidim-proposals/app/forms/decidim/proposals/concerns/formatted_attributes.rb
- decidim-proposals/app/forms/decidim/proposals/proposal_form.rb
Capitalize title and body for the user is more friendly and avoid the frustration of getting your proposals rejected for a typo, or because you don't know it was mandatory.
- Fixes #248
> Proposals caps first (for MEL)

- CHANGELOG.md
- decidim-core/app/validators/etiquette_validator.rb
- decidim-core/spec/validators/etiquette_validator_spec.rb
- decidim-proposals/app/commands/decidim/proposals/admin/create_proposal.rb
- decidim-proposals/app/commands/decidim/proposals/create_proposal.rb
- decidim-proposals/app/commands/decidim/proposals/update_proposal.rb
- decidim-proposals/app/forms/decidim/proposals/admin/proposal_form.rb
- decidim-proposals/app/forms/decidim/proposals/concerns/formatted_attributes.rb
- decidim-proposals/app/forms/decidim/proposals/proposal_form.rb
- decidim-proposals/spec/commands/decidim/proposals/update_proposal_spec.rb
- decidim-proposals/spec/shared/create_proposal_examples.rb
Capitalize title and body for the user is more friendly and avoid the frustration of getting your proposals rejected for a typo, or because you don't know it was mandatory.
- Fixes #248
> Proposals caps first

- CHANGELOG.md
- decidim-budgets/app/assets/stylesheets/decidim/budgets/budget/_budget-card.scss
- decidim-budgets/app/assets/stylesheets/decidim/budgets/budget/_budget-list.scss
- decidim-budgets/app/views/decidim/budgets/projects/_project.html.erb
- decidim-core/app/forms/decidim/attachment_form.rb
Fix display of budgets when votes count is activated
- Fixes #266
> Fix display of budgets when votes count is activated

- decidim-admin/app/views/decidim/admin/components/edit.html.erb
- decidim-admin/app/views/decidim/admin/components/new.html.erb
It used to be possible to select both votes module (simple & for/against/neutral).
Now it's not possible anymore :nail_care:
- Fixes #287
> Fix vote module checkbox in proposals

- CHANGELOG.md
- decidim-admin/app/forms/decidim/admin/managed_user_promotion_form.rb
- decidim-admin/spec/commands/decidim/admin/promote_managed_user_spec.rb
- decidim-admin/spec/forms/managed_user_promotion_form_spec.rb
Add validation to Managed User Promotion Form to avoid an unexplicit error on the form.
- Fixes #294
> Add email validation to Managed User Promotion Form

- decidim-core/lib/decidim/form_builder.rb
When only one locale is activated, the asterisk for required field is missing.
> :bug: fix translatable_presence asterisk when only one locale

- decidim-accountability/app/presenters/decidim/accountability/result_presenter.rb
- decidim-accountability/lib/decidim/accountability.rb
- decidim-accountability/lib/decidim/accountability/engine.rb
- decidim-accountability/lib/decidim/content_parsers/result_parser.rb
- decidim-accountability/lib/decidim/content_renderers/result_renderer.rb
- decidim-budgets/app/presenters/decidim/budgets/project_presenter.rb
- decidim-budgets/lib/decidim/budgets.rb
- decidim-budgets/lib/decidim/budgets/engine.rb
- decidim-budgets/lib/decidim/content_parsers/project_parser.rb
- decidim-budgets/lib/decidim/content_renderers/project_renderer.rb
- decidim-proposals/lib/decidim/content_parsers/proposal_parser.rb
Detected with #421 : Component object path (like Results or Projects) are interpreted as Proposals when adding a link in a comment.
> We might leave this one opened to push it to `0.16-stable`
This PR intend to : 
- check the embed link for actual reference to `/proposals/` in their path
- add the same mecanism for `Accountability` `Results`
- add the same mecanism for `Budgets` `Projects`
- the new content processors should check for their "model" in the parsed urls (like the fix for `/proposals/`)
- Fixes #421
> Fix/0.12 NEW content processors

- decidim-accountability/lib/decidim/accountability/result_serializer.rb
- decidim-comments/lib/decidim/comments/comment_serializer.rb
- decidim-core/app/helpers/decidim/translations_helper.rb
- decidim-proposals/lib/decidim/proposals/proposal_serializer.rb
- decidim-surveys/lib/decidim/surveys/survey_user_answers_serializer.rb
:bug: #417 : fix exports translatable_attr when first line is empty
Mainly aim to fix #417, but will provides a few fixes for exports for `0.12-stable` ++
- add `empty_translatable` helper to provide blank values
- fix `Decidim::Proposals::ProposalSerializer`
- fix `Decidim::Comments::CommentSerializer`
- fix `Decidim::Accountability::ResultSerializer`
- fix `Decidim::Surveys::SurveyUserAnswersSerializer`
- add `created_at` to survey answer export
- **TODO** : need specific tests on headers
- Fixes #417 
- Fixes #360 
- Add #226
> 0.12 - Exports fixes

- decidim-core/app/helpers/decidim/application_helper.rb
- decidim-participatory_processes/app/cells/decidim/participatory_processes/process_m_cell.rb
- decidim-participatory_processes/app/helpers/decidim/participatory_processes/participatory_process_helper.rb
- decidim-participatory_processes/app/views/decidim/participatory_processes/participatory_processes/_promoted_process.html.erb
- decidim-participatory_processes/spec/system/participatory_processes_spec.rb
Fix action btn text when a participatory process is created without it.
- Fixes #407
> Fix empty action btn text

- decidim-accountability/app/views/decidim/accountability/results/_show_leaf.html.erb
Fix Layout issue on accountability
- Fixes #143
> Fix Layout issue on accountability

- CHANGELOG.md
- decidim-debates/lib/decidim/debates/component.rb
- decidim-debates/lib/decidim/debates/debate_serializer.rb
- decidim-debates/spec/services/decidim/debates/debate_serializer_spec.rb
- decidim-debates/spec/shared/export_debates_examples.rb
Restore the Export feature on Debates component 
- Fixes #632
> Restore Debates export form component manifest

- CHANGELOG.md
- decidim-core/app/views/decidim/devise/shared/_omniauth_buttons_mini.html.erb
- decidim-core/app/views/decidim/shared/_login_modal.html.erb
Inverse blocks on the login modal so the user experience is more intuitive.
- Fixes #722
> Inverse blocks on login modal

- CHANGELOG.md
- decidim-budgets/config/locales/fr.yml
- decidim-forms/app/commands/decidim/forms/answer_questionnaire.rb
- decidim-forms/app/controllers/decidim/forms/concerns/has_questionnaire.rb
- decidim-forms/app/forms/decidim/forms/questionnaire_form.rb
- decidim-forms/app/models/decidim/forms/answer.rb
- decidim-forms/app/models/decidim/forms/questionnaire.rb
- decidim-forms/app/queries/decidim/forms/questionnaire_user_answers.rb
- decidim-forms/app/views/decidim/forms/questionnaires/show.html.erb
- decidim-forms/config/locales/en.yml
- decidim-forms/db/migrate/20190315203056_add_session_token_to_decidim_forms_answers.rb
- decidim-forms/db/migrate/20190930094710_add_ip_hash_to_decidim_form_answers.rb
- decidim-forms/lib/decidim/forms/user_answers_serializer.rb
- decidim-forms/spec/commands/decidim/forms/answer_questionnaire_spec.rb
- decidim-forms/spec/forms/decidim/forms/questionnaire_form_spec.rb
- decidim-meetings/app/controllers/decidim/meetings/registrations_controller.rb
- decidim-meetings/spec/commands/join_meeting_spec.rb
- decidim-surveys/app/controllers/decidim/surveys/surveys_controller.rb
- decidim-surveys/app/permissions/decidim/surveys/permissions.rb
- decidim-surveys/config/locales/en.yml
- decidim-surveys/config/locales/fr.yml
- decidim-surveys/lib/decidim/surveys/component.rb
- decidim-surveys/spec/system/unregistered_user_survey_spec.rb
* Add allow_unregistered option to surveys component
* locales for allow_unregistered settings action
* relax permissions to allow answers withou users
* Add session token to answer for grouping anonymous answers
* check if an unregistered user has already answered the questionnaire
* add unregistered users test
* rubocop happiness
* change test to match new locale messages
* add changelog entry [ci skip]
* unregisterd users settings warning
* add ip hash to unregistered surveys
* add invisible_captcha to forms
* Add user status to answers export
* remove unused key
* avoid NULL column
* use current instead of now
* refactor questionnaire validation for unregistered users
* simplify questionnaire validation and fix meetings reuse
* fix meetings tests
> Surveys for unregistered users (#4996)

- decidim-accountability/app/views/decidim/accountability/results/_show_leaf.html.erb
- decidim-accountability/app/views/decidim/accountability/results/_show_parent.html.erb
- decidim-accountability/config/locales/en.yml
- decidim-accountability/spec/system/explore_results_spec.rb
- decidim-blogs/app/views/decidim/blogs/posts/show.html.erb
- decidim-blogs/config/locales/en.yml
- decidim-blogs/config/locales/fr.yml
- decidim-blogs/spec/system/explore_posts_spec.rb
- decidim-budgets/config/locales/fr.yml
- decidim-debates/app/views/decidim/debates/debates/show.html.erb
- decidim-debates/config/locales/en.yml
- decidim-debates/config/locales/fr.yml
- decidim-debates/spec/system/show_spec.rb
- decidim-meetings/app/views/decidim/meetings/meetings/show.html.erb
- decidim-meetings/config/locales/en.yml
- decidim-meetings/config/locales/fr.yml
- decidim-meetings/spec/system/show_spec.rb
- decidim-proposals/app/views/decidim/proposals/proposals/show.html.erb
- decidim-proposals/config/locales/en.yml
- decidim-proposals/config/locales/fr.yml
- decidim-proposals/spec/system/show_spec.rb
- decidim-sortitions/app/views/decidim/sortitions/sortitions/show.html.erb
- decidim-sortitions/config/locales/en.yml
- decidim-sortitions/spec/system/decidim/sortitions/show_spec.rb
Add a "back to the list" button on the FO allowing user to go back to the component list
As a user, when clicking on a card on the Index, I want to be able to return to the list of cards (index) easily.
This button should be available on the cards of :
- Proposals
- News
- Meetings
- Sortitions
- Debates
https://meta.decidim.org/processes/roadmap/f/122/proposals/14938
> Add a "Return" button in the FO to get back to indexes

- decidim-core/app/models/decidim/organization.rb
- decidim-core/spec/models/decidim/organization_spec.rb
Meetings of an unpublished Participatory process are displayed on the "Upcoming events" section of the Homepage.
* Issue: OpenSourcePolitics/decidim#882
**To reproduce :** 
- Create a PP
- Create Meetings component
- Create a meeting
- Activate the "Upcoming events" on the Homepage
- See error
> Fix meetings displaying when process is not published

- decidim-core/app/helpers/decidim/image_responsive_helper.rb
- decidim-core/app/uploaders/decidim/banner_image_uploader.rb
- decidim-core/spec/helpers/decidim/image_responsive_helper_spec.rb
Image helper which allows to implement responsive image tag. This helper display the most adapted 
image version according to the user screen.
According to the mozilla definition, the Picture tag behaviour allows to display image even if the browser doesn't support this tag : 
> If no matches are found—or the browser doesn't support the <picture> element—the URL of the <img> element's src attribute is selected. The selected image is then presented in the space occupied by the <img> element.
The html tag used for this helper is supported by multiple browsers (cf: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture)
- Fixes OpenSourcePolitics/decidim#846
This helper works on several browsers (screenshot from Browserstack according to the review) 
* edge-79:beta
* ie-11:latest …
> Image responsive helper - OpenSourcePolitics/decidim#846

- decidim-forms/app/controllers/decidim/forms/concerns/has_questionnaire.rb
- decidim-forms/app/forms/decidim/forms/questionnaire_form.rb
- decidim-forms/spec/forms/decidim/forms/questionnaire_form_spec.rb
- decidim-meetings/spec/commands/join_meeting_spec.rb
We noticed that the survey component was querying the whole answers table when instantiated.
In `decidim-forms/app/controllers/decidim/forms/concerns/has_questionnaire.rb`:
```ruby
def show
@form = form(Decidim::Forms::QuestionnaireForm).from_model(questionnaire)
render template: "decidim/forms/questionnaires/show"
end
```
The consequence was the questionnaire answers were queried, and replaced by the questions.
For a 3370 answers survey, the number of queries needed to render the form was:
6486 request -> 52680 ms in local env
After this fix it was:
38 request -> 37 ms in local env
related to:
https://github.com/decidim/decidim/issues/5697
before: 
After:
> Avoid n+1 query on Surveys

- decidim-core/app/jobs/decidim/export_job.rb
- decidim-core/lib/decidim/exporters/csv.rb
- decidim-core/lib/decidim/exporters/excel.rb
- decidim-core/lib/decidim/exporters/json.rb
- decidim-core/spec/lib/exporters/csv_spec.rb
- decidim-core/spec/lib/exporters/excel_spec.rb
- decidim-core/spec/lib/exporters/json_spec.rb
- decidim-proposals/lib/decidim/proposals/proposal_serializer.rb
- decidim-proposals/spec/services/decidim/proposals/proposal_serializer_spec.rb
Add some fields for the proposals exports from backoffice. 
Also, add a logic to add more fields in proposals exports only for administrator exports and not exported in open data.
> Feature cd44 export proposals

- decidim-core/app/forms/decidim/registration_form.rb
- decidim-core/config/locales/en.yml
- decidim-core/config/locales/fr.yml
- decidim-core/spec/forms/registration_form_spec.rb
- decidim-core/spec/system/registration_spec.rb
When a user try to registrer on the platform, if he / she insert special chars in nickname or name, the validation will fail but no message is displayed. 
So a error message is now displayed when nickname or name field contains one or more special characters.
> Special characters message for new registration

- decidim-core/app/commands/decidim/create_registration.rb
- decidim-core/app/controllers/decidim/devise/registrations_controller.rb
- decidim-core/app/forms/decidim/registration_form.rb
- decidim-core/spec/commands/decidim/create_registration_spec.rb
- decidim-core/spec/system/authentication_spec.rb
Allow users to register in their own language
- Fixes #?
> Allow users to register in their own language

- decidim-comments/lib/decidim/comments/comment_serializer.rb
Add a new field in comment export when upstream moderation is enabled.
> add new 'published_at' field in comment export

- config/i18n-tasks.yml
- decidim-assemblies/config/locales/en.yml
- decidim-participatory_processes/app/controllers/decidim/participatory_processes/participatory_processes_controller.rb
- decidim-participatory_processes/app/helpers/decidim/participatory_processes/participatory_process_helper.rb
- decidim-participatory_processes/app/views/decidim/participatory_processes/participatory_processes/show.html.erb
- decidim-participatory_processes/config/locales/en.yml
- decidim-participatory_processes/spec/system/participatory_processes_spec.rb
:tophat: What? Why?
Add related assemblies to a participatory process
:clipboard: Subtasks
:camera: Screenshots (optional)
> Backport related assemblies in pp

- decidim-assemblies/app/views/decidim/assemblies/assemblies/show.html.erb
Change filter child assemblies option from slug to title
> filter child assemblies by title

- decidim-core/app/cells/decidim/progress_bar/show.erb
- decidim-core/lib/decidim/view_model.rb
- decidim-initiatives/config/locales/en.yml
- decidim-initiatives/config/locales/fr.yml
- decidim-initiatives/config/locales/nl.yml
Client needs to have a decimal delimiter for signatures number
> Add number delimiter to progress and total signatures number

- Gemfile
- Gemfile.lock
- config/i18n-tasks.yml
- decidim-admin/config/locales/en.yml
- decidim-core/db/migrate/20200518145440_add_sessions_table.rb
- decidim-core/lib/decidim/core/engine.rb
- decidim-initiatives/app/helpers/decidim/initiatives/initiative_helper.rb
- decidim-initiatives/app/models/decidim/initiative.rb
- decidim-initiatives/app/views/decidim/initiatives/initiative_signatures/fill_personal_data.html.erb
- decidim-initiatives/config/locales/en.yml
- decidim-initiatives/config/locales/fr.yml
- decidim-initiatives/spec/models/decidim/initiative_spec.rb
- decidim-initiatives/spec/system/initiatives_spec.rb
- decidim_app-design/Gemfile.lock
When user navigates to initiatives index, some initiatives have a different state on index and show page. 
When the state is "debatted" or "examinated", the initiative will be display as "created" 
Personal fields form
> Fix state translations in initiatives cards

- CHANGELOG.md
- Gemfile
- Gemfile.lock
- config/i18n-tasks.yml
- decidim-admin/config/locales/en.yml
- decidim-core/db/migrate/20200518145440_add_sessions_table.rb
- decidim-core/lib/decidim/core/engine.rb
- decidim-initiatives/app/controllers/concerns/decidim/initiatives/admin/filterable.rb
- decidim-initiatives/app/models/decidim/initiative.rb
- decidim-initiatives/config/locales/en.yml
- decidim-initiatives/spec/system/admin/admin_manages_initiatives_spec.rb
- decidim-initiatives/spec/system/initiatives_spec.rb
- decidim_app-design/Gemfile.lock
Enable admins to filter initiatives by type
- Metadecidim proposal: https://meta.decidim.org/processes/roadmap/f/122/proposals/15236
> Backport add filter initiative type admin

- .github/workflows/ci_initiatives.yml
- decidim-initiatives/app/helpers/decidim/initiatives/application_helper.rb
- decidim-initiatives/app/models/decidim/initiative.rb
- decidim-initiatives/app/services/decidim/initiatives/initiative_search.rb
- decidim-initiatives/config/locales/en.yml
- decidim-initiatives/spec/services/decidim/initiatives/initiative_search_spec.rb
- decidim-initiatives/spec/system/filter_initiatives_spec.rb
- decidim-initiatives/spec/system/initiatives_spec.rb
Add filter options "published", "classified", "examinated", "debatted" in initiatives.
Ensure "validating" and "created" state initiatives are not shown in FO because not published.
> Add states in initiatives filter

- .github/workflows/ci_initiatives.yml
- decidim-initiatives/app/controllers/concerns/decidim/initiatives/orderable.rb
- decidim-initiatives/app/models/decidim/initiative.rb
- decidim-initiatives/config/locales/en.yml
- decidim-initiatives/config/locales/fr.yml
- decidim-initiatives/spec/controllers/decidim/initiatives/initiatives_controller_spec.rb
- decidim-initiatives/spec/system/initiatives_spec.rb
Add a sorting option for "Answer date"  in FO
> Feature petition add sorting option

- decidim-initiatives/app/views/decidim/initiatives/admin/initiatives/index.html.erb
- decidim-initiatives/config/locales/en.yml
- decidim-initiatives/config/locales/fr.yml
Add new filter option in initiatives admin panel to sort by `answer_date`
> Add answer date sort in BO

- decidim-initiatives/app/cells/decidim/initiatives/initiative_m_cell.rb
- decidim-initiatives/app/models/decidim/initiative.rb
- decidim-initiatives/app/services/decidim/initiatives/initiative_search.rb
- decidim-initiatives/app/views/decidim/initiatives/admin/initiatives/index.html.erb
- decidim-initiatives/lib/decidim/initiatives/test/factories.rb
- decidim-initiatives/spec/models/decidim/initiative_spec.rb
Allows admin to sort initiatives by support count
> Fix support count sort in BO

- decidim-initiatives/app/controllers/decidim/initiatives/create_initiative_controller.rb
- decidim-initiatives/app/views/decidim/initiatives/create_initiative/finish.html.erb
- decidim-initiatives/app/views/layouts/decidim/_initiative_creation_header.html.erb
- decidim-initiatives/spec/system/create_initiative_spec.rb
**Comportement actuel**
- Quand le nombre min de membre pour le comité promoteur est fixé à `0`
- L'étape "Ajout de co-auteur" n' `apparaît pas`
- Le bouton "Envoyer à la validation technique" est lui bien présent sur l'étape du wizard
- Dans le back-office il est possible de rajouter des co-auteurs
- Quand le nombre min de membre pour le comité promoteur est fixé à `1`
- L'étape "Ajout de co-auteur" `apparaît` dans le wizard
- Le bouton "Envoyer à la validation technique" n'est  `pas présent` sur l'étape du wizard
NB : l'auteur d'une pétition est directement ajouté au comité de promotion, quand le nombre min de membre est fixé à 1 il est possible d'envoyer la pétition à la validation technique.
**Les changements de cette PR**
Quand le `comité de promotion est activé` et que le nombre min …
> [WIP] - Display button "send to technical validation" in initiative create form

- decidim-initiatives/app/views/decidim/initiatives/create_initiative/fill_data.html.erb
When user is creating an initiative, the text value of 'continue' button in fill data step turns to 'true' when disabled.
> Update text value when disabled button 'continue'

- decidim-initiatives/app/forms/decidim/initiatives/admin/initiative_answer_form.rb
- decidim-initiatives/spec/forms/admin/initiative_answer_form_spec.rb
At the moment in the initiative answer form, the answer date can't be today. 
The initial specification is that the answer date cannot be in the future, but it can be today.
> Enable answer date in initiatives to be set to current day

- decidim-initiatives/app/permissions/decidim/initiatives/admin/permissions.rb
- decidim-initiatives/spec/permissions/decidim/initiatives/admin/permissions_spec.rb
At the moment the PDF signature export button is only available on Published, Accepted or Rejected initiatives in BO.
It should also be available on the following custom states :
- Examinated
- Debatted
- Classified
> update export_signature_pdf permissions to accept manual states

- decidim-initiatives/app/models/decidim/initiative.rb
At the moment, the published initiatives are the only ones compared with the created initiative.
Now, it compares with all initiatives with a not null published_at value.
> Compare with custom state in initiatives comparator

- decidim-initiatives/app/forms/decidim/initiatives/admin/initiative_answer_form.rb
- decidim-initiatives/app/views/decidim/initiatives/admin/answers/edit.html.erb
- decidim-initiatives/spec/system/admin/answer_initiative_spec.rb
When trying to answer a discarded initiative, the first time I click on "Answer", I find an error message "Une erreur est survenue", and the 2nd time I find a routing error. 
Now, admin can answer initiative with automatic or manual states
> Fix admin answer form

- decidim-initiatives/app/views/decidim/initiatives/admin/answers/edit.html.erb
- decidim-initiatives/spec/system/admin/answer_initiative_spec.rb
When an initiative is given a custom state in the initiative answer form, the answer date must automatically be set on current date
> Update default answer date

- decidim-initiatives/app/controllers/decidim/initiatives/admin/answers_controller.rb
- decidim-initiatives/spec/system/admin/answer_initiative_spec.rb
When an admin answers to an initiative, with an invalid form, he / she is not redirected to the answer edit route. Then if the admin tries to submit again, a 404 error append.
- Fixes #?
> Backport answer form redirection

- decidim-initiatives/app/forms/decidim/initiatives/admin/initiative_answer_form.rb
- decidim-initiatives/app/views/decidim/initiatives/admin/answers/edit.html.erb
- decidim-initiatives/spec/forms/admin/initiative_answer_form_spec.rb
When changing an initiative custom state on the answer form, the form is not validated and I find an error message. 
All the other fields of the admin form are working. The error only happens when you change the custom state.
> refactor state logic for answer form

- decidim-initiatives/app/serializers/decidim/initiatives/initiative_serializer.rb
- decidim-initiatives/spec/serializers/decidim/initiatives/initiative_serializer_spec.rb
As an admin, when exporting the initiatives, I want to be able to see the number of different scopes the "signataires" chose.
> Add firms/scopes column in initiatives exports

- decidim-initiatives/app/mailers/decidim/initiatives/initiatives_mailer.rb
- decidim-initiatives/app/services/decidim/initiatives/status_change_notifier.rb
Email notifications are disabled for authors because an error occurs. This error appends because of the third param in `notify_state_change` method.
> Remove extra param in notify_state_change

- decidim-admin/app/views/decidim/admin/dashboard/show.html.erb
- decidim-initiatives/spec/system/admin/update_initiative_spec.rb
When user is not admin, she / he should not see the admin Terms of User in dashboard because it only concerns administrators 
- Fixes #?
> disable admin TOS for iniatives authors

- decidim-initiatives/app/cells/decidim/initiatives_votes/vote/show.erb
- decidim-initiatives/app/cells/decidim/initiatives_votes/vote_cell.rb
- decidim-initiatives/app/forms/decidim/initiatives/vote_form.rb
- decidim-initiatives/app/models/decidim/initiatives_vote.rb
- decidim-initiatives/app/serializers/decidim/initiatives/initiative_serializer.rb
- decidim-initiatives/spec/serializers/decidim/initiatives/initiative_serializer_spec.rb
Fix the "firms/scopes"  column that display the number of different scopes of the "signataires"
For exemple, 5 users signed the initiative, with the following scopes :
- 46 - Lot
- 75 - Paris
- 46 - Lot
- 81 - Haute-Garonne
- 75 - Paris
→ The number displayed should be "3" (46, 75, 81)
> Fix initiative firms scopes

- decidim-initiatives/app/views/decidim/initiatives/initiatives_mailer/_initiative_link.html.erb
- decidim-initiatives/app/views/decidim/initiatives/initiatives_mailer/notify_creation.html.erb
By default, Mailjet will rewrite urls to be shortened. According to mailjet's documentation `rel="notrack"` attribute should avoid the url rewriting
> add rel='notrack' attribute on mailer links

- decidim-core/app/commands/decidim/destroy_account.rb
- decidim-core/spec/commands/decidim/destroy_account_spec.rb
When admin removes his / her account, the admin role is kept. It occurs an empty row in the BO users index.
This PR removes the admin role when destroying account, if the current user is admin.
- Related to https://github.com/decidim/decidim/issues/6310
> Backport destroy admin account

- decidim-initiatives/app/models/decidim/initiative.rb
- decidim-initiatives/spec/mailers/decidim/initiatives/initiatives_mailer_spec.rb
When initiative's state changes, the notification sent shows the previous state.
This behaviour seems to occur because of race condition. In fact, in initiative model, notify_state_change method is called with after_save.
> status notifier backport

- decidim-initiatives/app/controllers/decidim/initiatives/admin/answers_controller.rb
- decidim-initiatives/app/views/decidim/initiatives/admin/answers/edit.html.erb
- decidim-initiatives/spec/system/admin/answer_initiative_spec.rb
Because of controller redirection, errors message from answer form validation are no longer visible
> fix missing validations after redirection

- decidim-core/app/cells/decidim/notifications/show.erb
- decidim-core/spec/system/notifications_spec.rb
The [demo of OSP](demo.decidim.opensourcepolitics.eu) got a servor error when accessing to the notifications page. This error is due to the presence in the database of notifications that were readable in version 0.16, but not anymore in 0.21.
We'll first deal with this issue by skiping the notification display if it isn't recognized anymore. Further improvements in the database may also be done afterwards.
- Fixes #?
~~- [ ] Add/modify seeds~~
> Fix notifications index error

- decidim-core/app/jobs/decidim/export_job.rb
- decidim-core/app/services/decidim/open_data_exporter.rb
- decidim-core/spec/services/decidim/open_data_exporter_spec.rb
At the moment, moderated proposals are exported in Open Data and when administrator exports the proposals.
The wanted behaviour is to only export visible proposals
> Remove moderated proposals in export

- decidim-core/config/locales/en.yml
- decidim-core/config/locales/fr.yml
- decidim-initiatives/app/forms/decidim/initiatives/admin/initiative_answer_form.rb
When giving an initiative a custom state, I can't put an answer date on a date before the current date.
Hope this PR will fix the current bug. I decided to create a specific validation to avoid that the limit date is frozen according [to this answer](https://stackoverflow.com/questions/8512691/how-to-validate-the-date-such-that-it-is-after-today-in-rails/8512796#comment66739831_37945477)
> Fix answer date form

- decidim-initiatives/app/assets/javascripts/decidim/initiatives/admin/initiatives_answer.js.es6
- decidim-initiatives/spec/system/admin/answer_initiative_spec.rb
When an admin answers to an initiative, or update an answer, and choose the "classified" state, the `signature_end_date` is automatically set to current date.
> Set signature_end_date to current date for classified initiatives

- decidim-participatory_processes/app/serializers/decidim/participatory_processes/participatory_process_serializer.rb
- decidim-participatory_processes/spec/serializers/decidim/participatory_processes/participatory_process_serializer_spec.rb
Participatory processes are no longer exported and raising an error related to the `private_cope` parameter.
This is probably related to the commit 7e32803 and was never detected before.
- Fixes #1046
> Fix participatory_process export

- decidim-core/app/cells/decidim/tos_page/sticky_form.erb
When user signs in, she is redirected to the term and conditions page in order to accept them. However, the content of the TOS is not displayed anymore, and in some case not selectable or clickable.
Steps to reproduce the behavior:
Go to 'sign in' page
Log in with user which has not accepted TOS
See missing TOS content
User expects to see the TOS content and to be able to click link if there is some links in the TOS.
> Fix broken tos display

- decidim-initiatives/app/services/decidim/initiatives/status_change_notifier.rb
- decidim-initiatives/spec/services/decidim/initiatives/status_change_notifier_spec.rb
When administrator switches off `email_on_notification`, technical validation notifications are still sent by email.
> Don't send technical validation email when not email_on_notifications 

- decidim-core/app/jobs/decidim/event_publisher_job.rb
- decidim-core/app/services/decidim/email_notification_generator.rb
- decidim-dev/lib/decidim/dev/test/rspec_support/action_mailer.rb
- decidim-initiatives/app/commands/decidim/initiatives/vote_initiative.rb
- decidim-initiatives/spec/commands/decidim/initiatives/vote_initiative_spec.rb
When initiative vote count reached 100%, admin should receive notification.
> Fix notification threshold reached

- decidim-dev/decidim-dev.gemspec
Rubocop-rails needs at least the version `v0.71.0` of rubocop for running correctly in [osp-app](https://github.com/Quentinchampenois/osp-app-toulouse)
Furthermore, the official [Decidim v0.18.0 dev gemspec](https://github.com/decidim/decidim/blob/release/0.18-stable/decidim-dev/decidim-dev.gemspec) has already bump the rubocop version.
> bump rubocop version

- decidim-initiatives/app/controllers/decidim/initiatives/create_initiative_controller.rb
- decidim-initiatives/app/helpers/decidim/initiatives/create_initiative_helper.rb
- decidim-initiatives/app/views/decidim/initiatives/create_initiative/finish.html.erb
- decidim-initiatives/app/views/layouts/decidim/_initiative_creation_header.html.erb
- decidim-initiatives/spec/system/create_initiative_spec.rb
As a user, I don't see the promoting committee step in initiative creation wizard, although min promoting committee = 1. 
As an admin, when enabling promoting committee and setting it to 1, I expect to:
- See the promoting committee step in the initiative creation wizard
- See the "Send to technical validation" button at last step of the wizard.
> Fix promoting committee wizard

- decidim-initiatives/app/events/decidim/initiatives/spawn_committee_request_event.rb
- decidim-initiatives/config/locales/en.yml
- decidim-initiatives/spec/events/decidim/initiatives/spawn_committee_request_event_spec.rb
As an author, when I receive a mail about co-authors, I want to know the name of the applicant instead of her nickname. 
:hearts: Thank you!
> Fix committee request email name
